webtalk_init -webtalk_dir C:/Users/Docencia/Desktop/Entregable3-20211108T171246Z-001/GreatestCommonDivider/GreatestCommonDivider.sim/sim_1/behav/xsim/xsim.dir/Nombre_Entidad_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 15 20:02:04 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174123010_174123011_210662615_504" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9bc23716-6b25-491f-9732-123f9caa02b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2bfcc7cbc5834f6f8ff52b3e26f27821" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5668_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3210053564 -regid "174123010_174123011_210662615_504" -xml C:/Users/Docencia/Desktop/Entregable3-20211108T171246Z-001/GreatestCommonDivider/GreatestCommonDivider.sim/sim_1/behav/xsim/xsim.dir/Nombre_Entidad_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Docencia/Desktop/Entregable3-20211108T171246Z-001/GreatestCommonDivider/GreatestCommonDivider.sim/sim_1/behav/xsim/xsim.dir/Nombre_Entidad_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Docencia/Desktop/Entregable3-20211108T171246Z-001/GreatestCommonDivider/GreatestCommonDivider.sim/sim_1/behav/xsim/xsim.dir/Nombre_Entidad_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
